name: Mise à jour du badge

on:
    push:
        branches:
            - main

permissions:
  contents: write

jobs:
    update-badge:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout du dépôt
              uses: actions/checkout@v3

            - name: Compter le nombre de commits
              id: commit_count
              run: echo "::set-output name=count::$(git rev-list --count HEAD)"

            - name: Mettre à jour le badge
              run: |
                echo '{
                "schemaVersion": 1,
                "label": "Commits",
                "message": "'$(git rev-list --count HEAD)'",
                "color": "blue"
                }' > badges/badge.json

            - name: Commit et push les modifications
              run: |
                git config --global user.name "GitHub Actions"
                git config --global user.email "actions@github.com"
                git add badges/badge.json
                git commit -m "Mise à jour automatique du badge"
                git push